<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Poisson Linear Regression | Applied Machine Learning</title>
  <meta name="description" content="Chapter 3 Poisson Linear Regression | Applied Machine Learning" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Poisson Linear Regression | Applied Machine Learning" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Poisson Linear Regression | Applied Machine Learning" />
  
  
  

<meta name="author" content="Sheptim Veseli &amp; Eliana Perea Barreto" />


<meta name="date" content="2024-06-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple-linear-model.html"/>
<link rel="next" href="binomial-linear-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied ML</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#dataset"><i class="fa fa-check"></i><b>1.1</b> Dataset</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#the-models"><i class="fa fa-check"></i><b>1.2</b> The models</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#use-of-generative-ai"><i class="fa fa-check"></i><b>1.3</b> Use of Generative AI</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="simple-linear-model.html"><a href="simple-linear-model.html"><i class="fa fa-check"></i><b>2</b> Simple Linear Model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="simple-linear-model.html"><a href="simple-linear-model.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="simple-linear-model.html"><a href="simple-linear-model.html#data-preparation"><i class="fa fa-check"></i><b>2.2</b> Data Preparation</a></li>
<li class="chapter" data-level="2.3" data-path="simple-linear-model.html"><a href="simple-linear-model.html#descriptive-statistics"><i class="fa fa-check"></i><b>2.3</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="simple-linear-model.html"><a href="simple-linear-model.html#arrival-delay-statistics"><i class="fa fa-check"></i><b>2.3.1</b> Arrival Delay Statistics</a></li>
<li class="chapter" data-level="2.3.2" data-path="simple-linear-model.html"><a href="simple-linear-model.html#carrier-statistics"><i class="fa fa-check"></i><b>2.3.2</b> Carrier Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="simple-linear-model.html"><a href="simple-linear-model.html#linear-regression-analysis"><i class="fa fa-check"></i><b>2.4</b> Linear Regression Analysis</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="simple-linear-model.html"><a href="simple-linear-model.html#model-summary"><i class="fa fa-check"></i><b>2.4.1</b> Model Summary</a></li>
<li class="chapter" data-level="2.4.2" data-path="simple-linear-model.html"><a href="simple-linear-model.html#significant-carriers"><i class="fa fa-check"></i><b>2.4.2</b> Significant Carriers</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="simple-linear-model.html"><a href="simple-linear-model.html#diagnostic-plots"><i class="fa fa-check"></i><b>2.5</b> Diagnostic Plots</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="simple-linear-model.html"><a href="simple-linear-model.html#interpretation-and-conclusion"><i class="fa fa-check"></i><b>2.5.1</b> Interpretation and Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Poisson Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#overview"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#algorithmic-framework"><i class="fa fa-check"></i><b>3.2</b> Algorithmic Framework</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#data-nature"><i class="fa fa-check"></i><b>3.2.1</b> Data Nature</a></li>
<li class="chapter" data-level="3.2.2" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#regression-equation"><i class="fa fa-check"></i><b>3.2.2</b> Regression equation</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#training-predicting-process"><i class="fa fa-check"></i><b>3.3</b> Training &amp; Predicting Process</a></li>
<li class="chapter" data-level="3.4" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#strengths-limitations"><i class="fa fa-check"></i><b>3.4</b> Strengths &amp; Limitations</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#strengths"><i class="fa fa-check"></i><b>3.4.1</b> Strengths</a></li>
<li class="chapter" data-level="3.4.2" data-path="poisson-linear-regression.html"><a href="poisson-linear-regression.html#limitations"><i class="fa fa-check"></i><b>3.4.2</b> Limitations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html"><i class="fa fa-check"></i><b>4</b> Binomial Linear Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#overview-1"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#algorithmic-framework-1"><i class="fa fa-check"></i><b>4.2</b> Algorithmic Framework</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#data-nature-1"><i class="fa fa-check"></i><b>4.2.1</b> Data Nature</a></li>
<li class="chapter" data-level="4.2.2" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#regression-equation-1"><i class="fa fa-check"></i><b>4.2.2</b> Regression Equation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#training-predicting-process-1"><i class="fa fa-check"></i><b>4.3</b> Training &amp; Predicting Process</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#model-evaluation"><i class="fa fa-check"></i><b>4.3.1</b> Model Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#strengths-and-limitations"><i class="fa fa-check"></i><b>4.4</b> Strengths and Limitations</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#strengths-1"><i class="fa fa-check"></i><b>4.4.1</b> Strengths</a></li>
<li class="chapter" data-level="4.4.2" data-path="binomial-linear-regression.html"><a href="binomial-linear-regression.html#limitations-1"><i class="fa fa-check"></i><b>4.4.2</b> Limitations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="support-vector-machine.html"><a href="support-vector-machine.html"><i class="fa fa-check"></i><b>5</b> Support Vector Machine</a>
<ul>
<li class="chapter" data-level="5.1" data-path="support-vector-machine.html"><a href="support-vector-machine.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="support-vector-machine.html"><a href="support-vector-machine.html#data-preparation-1"><i class="fa fa-check"></i><b>5.2</b> Data Preparation</a></li>
<li class="chapter" data-level="5.3" data-path="support-vector-machine.html"><a href="support-vector-machine.html#training-and-test-split"><i class="fa fa-check"></i><b>5.3</b> Training and Test Split</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="support-vector-machine.html"><a href="support-vector-machine.html#svm-model-training"><i class="fa fa-check"></i><b>5.3.1</b> SVM Model Training</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="support-vector-machine.html"><a href="support-vector-machine.html#model-evaluation-1"><i class="fa fa-check"></i><b>5.4</b> Model Evaluation</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="support-vector-machine.html"><a href="support-vector-machine.html#result-interpretation"><i class="fa fa-check"></i><b>5.4.1</b> Result Interpretation</a></li>
<li class="chapter" data-level="5.4.2" data-path="support-vector-machine.html"><a href="support-vector-machine.html#discussion"><i class="fa fa-check"></i><b>5.4.2</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="support-vector-machine.html"><a href="support-vector-machine.html#conclusion"><i class="fa fa-check"></i><b>5.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html"><i class="fa fa-check"></i><b>6</b> Generalized Additive Model</a>
<ul>
<li class="chapter" data-level="6.1" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#data-preparation-2"><i class="fa fa-check"></i><b>6.2</b> Data Preparation</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#log-transformation"><i class="fa fa-check"></i><b>6.2.1</b> Log Transformation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#data-splitting-model-fitting"><i class="fa fa-check"></i><b>6.3</b> Data Splitting &amp; Model Fitting</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#model-summary-1"><i class="fa fa-check"></i><b>6.3.1</b> Model Summary</a></li>
<li class="chapter" data-level="6.3.2" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#model-evaluation-2"><i class="fa fa-check"></i><b>6.3.2</b> Model Evaluation</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="generalized-additive-model.html"><a href="generalized-additive-model.html#conclusion-1"><i class="fa fa-check"></i><b>6.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="neural-network.html"><a href="neural-network.html"><i class="fa fa-check"></i><b>7</b> Neural Network</a>
<ul>
<li class="chapter" data-level="7.1" data-path="neural-network.html"><a href="neural-network.html#overview-2"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="neural-network.html"><a href="neural-network.html#algorithmic-framework-2"><i class="fa fa-check"></i><b>7.2</b> Algorithmic Framework</a></li>
<li class="chapter" data-level="7.3" data-path="neural-network.html"><a href="neural-network.html#training-predicting-process-2"><i class="fa fa-check"></i><b>7.3</b> Training &amp; Predicting Process</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="neural-network.html"><a href="neural-network.html#feed-forward-algorithm"><i class="fa fa-check"></i><b>7.3.1</b> Feed-forward Algorithm</a></li>
<li class="chapter" data-level="7.3.2" data-path="neural-network.html"><a href="neural-network.html#backpropagation"><i class="fa fa-check"></i><b>7.3.2</b> Backpropagation</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="neural-network.html"><a href="neural-network.html#strengths-limitations-1"><i class="fa fa-check"></i><b>7.4</b> Strengths &amp; Limitations</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="neural-network.html"><a href="neural-network.html#strengths-2"><i class="fa fa-check"></i><b>7.4.1</b> Strengths</a></li>
<li class="chapter" data-level="7.4.2" data-path="neural-network.html"><a href="neural-network.html#limitations-2"><i class="fa fa-check"></i><b>7.4.2</b> Limitations</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/EliB29/AML" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Machine Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="poisson-linear-regression" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Poisson Linear Regression<a href="poisson-linear-regression.html#poisson-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>By Eliana Perea Barreto</p>
<div id="overview" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Overview<a href="poisson-linear-regression.html#overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Poisson regression stands as a powerful method suited for the analysis of count data, focusing on events expressed as whole numbers. Unlike linear regression, which handles continuous data, Poisson regression suits situations reflecting a Poisson distribution, where the dependent variable (y) represent counts within fixed temporal or spatial boundaries.</p>
</div>
<div id="algorithmic-framework" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Algorithmic Framework<a href="poisson-linear-regression.html#algorithmic-framework" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="data-nature" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Data Nature<a href="poisson-linear-regression.html#data-nature" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In contrast to continuous variables, Poisson Distribution data points are restricted to non-negative integers, where (y) can only assume values of zero or greater. Illustratively, let’s take a practical look to the implementation of this idea by analyzing the response variable (y) <code>arr_delay</code> from our study case which, as previously mentioned, is aimed at inspecting the relationship between carrier name and the frequency of flight delays.</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -59.000 -17.000  -4.000  -2.837   6.013  60.000</code></pre>
<p>Examining the dependent variable <code>arr_delay</code>, a main challenge arises as this predictor contains continuous values. To address this, the values are spitted into intervals of 3 minutes each. So that, the occurrence of arrival delays for each carrier can be quantified. Looking at the summary, it’s also possible to acknowledge that the median and mean reveals a prevalence of negative values deemed irrelevant, as the goal of this exercise is to inspect the relationship between the presence (not the absence) of arrival delays for each carrier. Thus, all values lower or equal to zero won’t be taken into consideration. Click on code preview to see how the data was counted and segmented by intervals of time.</p>
<details>
<p><summary><b style="font-size:90%; border: 1px solid gray; border-radius: 5px; padding: 5px; ">Code Preview </b></p>
</summary>
<pre><code>interval &lt;-seq(1, upper_bound+0.5, by = 3)  # 0.5 is needed as the count is asymmetrical. 

# Discretize arrival delays into intervals and count occurrences. 
delay_counts_1 &lt;- data_flight %&gt;%
  filter(arr_delay &gt; 0)%&gt;% 
  mutate(delay_interval = cut(arr_delay, breaks = interval,  right = T, include.lowest = T))%&gt;%
  group_by(delay_interval, carrier)%&gt;%
  summarise(delay_count = n())</code></pre>
</details>
<p>The distribution of the newly generated count data across time intervals serves as the model’s dependent variables and it is assigned to the predictor <code>delay_count</code>. In the visualization below, you’ll observe that darker shades indicate a higher frequency of events per delay interval of time and carrier name.</p>
<div class="plotly html-widget html-fill-item" id="htmlwidget-31d44eb86f795c627c65" style="width:672px;height:432px;"></div>
<script type="application/json" data-for="htmlwidget-31d44eb86f795c627c65">{"x":{"visdat":{"330026c81e76":["function () ","plotlyVisDat"]},"cur_data":"330026c81e76","attrs":{"330026c81e76":{"x":{},"y":{},"mode":"markers","text":{},"marker":{"size":10,"color":{}},"showlegend":true,"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Carrier: Airline name","type":"category","categoryorder":"array","categoryarray":["9E","AA","AS","B6","DL","EV","F9","FL","HA","MQ","OO","UA","US","VX","WN","YV"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Delay Interval","type":"category","categoryorder":"array","categoryarray":["[1,4]","(4,7]","(7,10]","(10,13]","(13,16]","(16,19]","(19,22]","(22,25]","(25,28]","(28,31]","(31,34]","(34,37]","(37,40]","(40,43]","(43,46]","(46,49]","(49,52]","(52,55]","(55,58]","(58,61]"]},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["9E","AA","AS","B6","DL","EV","F9","FL","MQ","UA","US","VX","WN","9E","AA","B6","DL","EV","F9","FL","HA","MQ","OO","UA","US","VX","WN","YV","9E","AA","B6","DL","EV","FL","MQ","UA","US","VX","WN","9E","AA","B6","DL","EV","F9","FL","MQ","UA","US","VX","WN","YV","9E","AA","B6","DL","EV","FL","MQ","UA","US","VX","WN","9E","AA","AS","B6","DL","EV","FL","MQ","UA","US","WN","9E","AA","B6","DL","EV","MQ","UA","US","VX","WN","9E","AA","B6","DL","EV","FL","MQ","UA","US","VX","WN","9E","AA","B6","DL","EV","MQ","UA","US","VX","WN","9E","AA","B6","DL","EV","MQ","UA","US","VX","AA","B6","DL","EV","FL","MQ","UA","US","WN","9E","AA","B6","DL","EV","MQ","UA","VX","9E","AA","B6","DL","EV","FL","MQ","UA","WN","9E","AA","B6","DL","EV","FL","MQ","UA","US","WN","9E","B6","DL","EV","MQ","UA","WN","9E","AA","B6","DL","EV","MQ","UA","US","WN","9E","B6","DL","EV","UA","US","WN","9E","AA","B6","DL","EV","FL","MQ","UA","9E","AA","B6","DL","EV","MQ","UA","US","WN","9E","AA","B6","DL","EV","MQ","UA","US","WN"],"y":["[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","[1,4]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(4,7]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(7,10]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(10,13]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(13,16]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(16,19]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(19,22]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(22,25]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(25,28]","(28,31]","(28,31]","(28,31]","(28,31]","(28,31]","(28,31]","(28,31]","(28,31]","(28,31]","(31,34]","(31,34]","(31,34]","(31,34]","(31,34]","(31,34]","(31,34]","(31,34]","(31,34]","(34,37]","(34,37]","(34,37]","(34,37]","(34,37]","(34,37]","(34,37]","(34,37]","(37,40]","(37,40]","(37,40]","(37,40]","(37,40]","(37,40]","(37,40]","(37,40]","(37,40]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(40,43]","(43,46]","(43,46]","(43,46]","(43,46]","(43,46]","(43,46]","(43,46]","(46,49]","(46,49]","(46,49]","(46,49]","(46,49]","(46,49]","(46,49]","(46,49]","(46,49]","(49,52]","(49,52]","(49,52]","(49,52]","(49,52]","(49,52]","(49,52]","(52,55]","(52,55]","(52,55]","(52,55]","(52,55]","(52,55]","(52,55]","(52,55]","(55,58]","(55,58]","(55,58]","(55,58]","(55,58]","(55,58]","(55,58]","(55,58]","(55,58]","(58,61]","(58,61]","(58,61]","(58,61]","(58,61]","(58,61]","(58,61]","(58,61]","(58,61]"],"mode":"markers","text":[7,32,1,43,35,43,2,7,21,55,23,4,17,51,58,111,85,152,1,8,1,76,1,93,42,9,22,1,2,16,18,25,22,2,9,38,11,2,6,8,9,24,11,24,1,3,11,25,5,7,4,1,7,12,24,22,19,3,13,20,6,1,3,7,10,1,19,16,14,2,8,11,4,1,6,8,10,17,17,13,16,3,1,3,7,7,18,6,11,2,10,9,6,2,5,2,8,5,9,9,7,6,4,1,5,5,5,16,5,11,6,11,2,1,3,8,3,8,1,5,7,4,2,3,4,11,2,12,5,8,1,4,1,10,2,8,1,3,6,1,3,4,6,3,9,1,9,5,3,4,1,6,3,4,1,4,3,1,1,7,2,4,3,5,1,1,1,4,5,8,4,2,2,2,3,3,4,5,1,1,6,1,3,3,1,6,1,4,2,1,1,4,1,1,6,1,1,1,1],"marker":{"color":[7,32,5,43,35,43,5,7,21,55,23,5,17,51,58,100,85,100,5,8,5,76,5,93,42,9,22,5,5,16,18,25,22,5,9,38,11,5,6,8,9,24,11,24,5,5,11,25,5,7,5,5,7,12,24,22,19,5,13,20,6,5,5,7,10,5,19,16,14,5,8,11,5,5,6,8,10,17,17,13,16,5,5,5,7,7,18,6,11,5,10,9,6,5,5,5,8,5,9,9,7,6,5,5,5,5,5,16,5,11,6,11,5,5,5,8,5,8,5,5,7,5,5,5,5,11,5,12,5,8,5,5,5,10,5,8,5,5,6,5,5,5,6,5,9,5,9,5,5,5,5,6,5,5,5,5,5,5,5,7,5,5,5,5,5,5,5,5,5,8,5,5,5,5,5,5,5,5,5,5,6,5,5,5,5,6,5,5,5,5,5,5,5,5,6,5,5,5,5],"size":10,"line":{"color":"rgba(31,119,180,1)"}},"showlegend":true,"type":"scatter","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<hr />
<p>As for the independent variable, it’s evident from the plot that the values in <code>carrier</code> are nominal categorical. Which is okey, as independent variables can be of any type in Poisson Regression. Sometimes they must be encoded appropriately before fitting the model, for instance through dummy variables, one-hot encoding or factorization. However in this case, as the main focus is on examining the association between delay counts and carrier identity with no other predictor variables included, the categorical variable “carrier” can directly be implemented in the model .</p>
</div>
<div id="regression-equation" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Regression equation<a href="poisson-linear-regression.html#regression-equation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A few things can be derived from the assumption that the dependent variable in a Poisson-like distribution represent counts events occurring within a fixed boundary. For example, if those data points were to be represented in the Cartesian plane, they would also exist in a fixed space. In this scenario, a standard regression line, which may also predict negative values, is unsuitable for Poisson regression. Look at the example below:</p>
<p><img src="r_squared_4.png" width="665" /></p>
<p>Notice that the line representing linear growth can very easily go below the origin at any given point while the starting point of the exponential line remains fixed. A non-linear relationship, typified by an exponential line, proves better-suited for this model. Consequently, the concept of exponential growth is included within the model’s regression equation, where a logarithmic transformation withholds the relationship between the dependent variable and the independent variable with its coefficients.</p>
<p><span class="math display">\[
y = e^{(\beta_0 + \beta_1x_1)} \quad\text{  or }\quad log(y) = \beta_0 + \beta_1x_1
\]</span></p>
<p>It’s essential to recognize that (y) symbolizes the incidence rate of an event per unit of exposure, rather than the count of observed events. Replaced by the symbol (λ) or notated along with y∼Poisson(λ), (y) is understood as a rate parameter. This idea is pivotal, as concepts like the mean and variance hinge on it. For instance, since (λ) denotes the average rate of event occurrences within a fixed interval, the mean (expected value) remains equivalent to (λ). Consequently, as the mean increases, the range of possible outcomes expands. In other words, the distribution’s variability increases, which emphasizes the symmetrical association between the mean and the variance in Poisson Distribution.</p>
<p><span class="math display">\[ \lambda = e^{(\beta_0 + \beta_1x)} \quad \quad \text{or} \quad \quad y=e^{(\beta_0 + \beta_1x_1)} \quad y\sim Poisson(\lambda) \]</span></p>
<p>Elements of this equation, such as the rate parameter (λ) and the coefficients (β0, β1), are automatically calculated through the implementation of the function GLM with family set to poisson <code>glm(..., family = "poisson")</code>.</p>
<p>Ultimately, before starting training or prediction, the model will be fitted with all available data to evaluate the accuracy of the model and the relationship of the variables.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="poisson-linear-regression.html#cb11-1" tabindex="-1"></a>poisson_model_eval <span class="ot">&lt;-</span> <span class="fu">glm</span>(delay_count <span class="sc">~</span> carrier, <span class="at">data =</span> delay_counts, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span></code></pre></div>
<details>
<p><summary><b style="font-size:90%; border: 1px solid gray; border-radius: 5px; padding: 5px; ">summary </b></p>
</summary>
<pre><code>## 
## Call:
## glm(formula = delay_count ~ carrier, family = &quot;poisson&quot;, data = delay_counts)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.83468    0.09166  20.016  &lt; 2e-16 ***
## carrierAA    0.51139    0.11714   4.366 1.27e-05 ***
## carrierAS   -1.83468    0.71302  -2.573 0.010079 *  
## carrierB6    1.01891    0.10622   9.592  &lt; 2e-16 ***
## carrierDL    0.71866    0.11087   6.482 9.05e-11 ***
## carrierEV    1.14085    0.10465  10.901  &lt; 2e-16 ***
## carrierF9   -1.54700    0.50833  -3.043 0.002340 ** 
## carrierFL   -0.79859    0.20164  -3.960 7.48e-05 ***
## carrierHA   -1.83468    1.00419  -1.827 0.067696 .  
## carrierMQ    0.53408    0.11544   4.626 3.72e-06 ***
## carrierOO   -1.83468    1.00419  -1.827 0.067696 .  
## carrierUA    0.98072    0.10675   9.187  &lt; 2e-16 ***
## carrierUS    0.17185    0.12963   1.326 0.184948    
## carrierVX   -0.76997    0.20709  -3.718 0.000201 ***
## carrierWN   -0.27345    0.14404  -1.898 0.057639 .  
## carrierYV   -1.83468    0.71302  -2.573 0.010079 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 3245.5  on 198  degrees of freedom
## Residual deviance: 2563.9  on 183  degrees of freedom
## AIC: 3295
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</details>
<p>The model seems to effectively capture significant correlations among the variables, as indicated by the majority of carrier coefficients exhibiting statistically significant p-values. However, carrier US stands out with a coefficient surpassing 0.05, suggesting its potential minimal impact on delay occurrences. Thus, it might be prudent to contemplate excluding carrier US from the model. Nevertheless, before making any adjustments, let’s explore other potential factors that might be affecting the accuracy of the model.</p>
<p>Notably, the coefficient estimates for carriers AS, OO, HA, and YV share an identical coefficient estimate of -1.83468 which is an unusual situation, unless these carriers are somehow grouped by a common circumstance. Upon reviewing the plot presented above, it’s apparent that these carriers are consistently associated with limited data, which is also evident by their relatively high standard errors (0.71302 for carriers AS and YV, and 1.00419 for carrier OO). The scarcity of data leads to less precise estimates, thus removing these coefficients might be a wise decision to improve the model’s reliability and predictive accuracy.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="poisson-linear-regression.html#cb13-1" tabindex="-1"></a>delay_counts_new <span class="ot">&lt;-</span> delay_counts[<span class="sc">!</span>(delay_counts<span class="sc">$</span>carrier <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;AS&quot;</span>, <span class="st">&quot;OO&quot;</span>, <span class="st">&quot;YV&quot;</span>, <span class="st">&quot;HA&quot;</span>)), ]</span>
<span id="cb13-2"><a href="poisson-linear-regression.html#cb13-2" tabindex="-1"></a>poisson_model_eval <span class="ot">&lt;-</span> <span class="fu">glm</span>(delay_count <span class="sc">~</span> carrier, <span class="at">data =</span> delay_counts_new, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span></code></pre></div>
<details>
<p><summary><b style="font-size:90%; border: 1px solid gray; border-radius: 5px; padding: 5px; ">summary </b></p>
</summary>
<pre><code>## 
## Call:
## glm(formula = delay_count ~ carrier, family = &quot;poisson&quot;, data = delay_counts_new)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.83468    0.09166  20.016  &lt; 2e-16 ***
## carrierAA    0.51139    0.11714   4.366 1.27e-05 ***
## carrierB6    1.01891    0.10622   9.592  &lt; 2e-16 ***
## carrierDL    0.71866    0.11087   6.482 9.05e-11 ***
## carrierEV    1.14085    0.10465  10.901  &lt; 2e-16 ***
## carrierF9   -1.54700    0.50833  -3.043 0.002340 ** 
## carrierFL   -0.79859    0.20164  -3.960 7.48e-05 ***
## carrierMQ    0.53408    0.11544   4.626 3.72e-06 ***
## carrierUA    0.98072    0.10675   9.187  &lt; 2e-16 ***
## carrierUS    0.17185    0.12963   1.326 0.184948    
## carrierVX   -0.76997    0.20709  -3.718 0.000201 ***
## carrierWN   -0.27345    0.14404  -1.898 0.057639 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 3157.0  on 192  degrees of freedom
## Residual deviance: 2563.9  on 181  degrees of freedom
## AIC: 3275
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</details>
<p>The residual deviance of the revised model remains at 2563.9, indicating that the overall model fit remains consistent even after excluding carriers AS, OO, HA and YV from the dataset. The decrease in the AIC value from 3295 to 3279 suggests a slight enhancement in model fit following the removal of the three carriers. However, the standard error and p-value for all coefficients remain unchanged, so carrier US still lacks significant influence, as evidenced by its p-value of 0.184948.</p>
</div>
</div>
<div id="training-predicting-process" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Training &amp; Predicting Process<a href="poisson-linear-regression.html#training-predicting-process" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Despite, GLM for Poisson regression doesn’t have specific built-in functions for training and testing like some machine learning algorithms, it can still be employed along with standard techniques for forecasting. Following the assesment of the data distribution, the subsequent phase involves dividing the dataset into training and testing subsets to evaluate the model’s performance. 80% of the data is allocated for GLM fitting while the remaining 20% is reserved for the evaluation the model’s predictive accuracy using the <code>predict()</code> function.</p>
<details>
<p><summary><b style="font-size:90%; border: 1px solid gray; border-radius: 5px; padding: 5px; ">Code Preview </b></p>
</summary>
<pre><code># Split the data (80% training, 20% testing)
index &lt;- sample(1:nrow(delay_counts_new), 0.8*nrow(delay_counts_new))
training_data &lt;- delay_counts_new[index, ]
testing_data &lt;- delay_counts_new[-index, ]</code></pre>
</details>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="poisson-linear-regression.html#cb16-1" tabindex="-1"></a>poisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(delay_count <span class="sc">~</span> carrier, <span class="at">data =</span> training_data, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb16-2"><a href="poisson-linear-regression.html#cb16-2" tabindex="-1"></a>predicted_counts <span class="ot">&lt;-</span> <span class="fu">predict</span>(poisson_model, <span class="at">newdata =</span> testing_data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<p>When assessing the precision of predictions generated by a Poisson regression model, various metrics can be utilized to measure the correspondence between the model’s predictions and the actual data. Nonetheless, let’s first initiate the process by gaining insight into the relationship between the predicted and the actual counts through a line plot..</p>
<div class="plotly html-widget html-fill-item" id="htmlwidget-8500ba61052a968e1c6c" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-8500ba61052a968e1c6c">{"x":{"visdat":{"330054023b93":["function () ","plotlyVisDat"]},"cur_data":"330054023b93","attrs":{"330054023b93":{"x":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"y":{},"type":"scatter","mode":"lines","name":"Actual","line":{"color":"blue"},"hoverinfo":"y+text","text":{},"inherit":true},"330054023b93.1":{"x":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"y":{},"type":"scatter","mode":"lines","name":"Predicted","line":{"color":"red"},"hoverinfo":"y+text","text":{},"inherit":true}},"layout":{"margin":{"b":90,"l":60,"t":25,"r":10},"title":"Actual vs. Predicted Counts by index in dataset","xaxis":{"domain":[0,1],"automargin":true,"title":"Index"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Count"},"legend":{"x":1,"y":0.5,"xanchor":"right","yanchor":"middle"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39],"y":[43,21,111,85,8,93,22,18,9,38,9,24,7,7,22,20,7,19,6,17,6,5,11,2,5,6,1,1,3,1,5,2,2,3,4,1,1,1,1],"type":"scatter","mode":"lines","name":"Actual","line":{"color":"blue"},"hoverinfo":["y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text"],"text":["Delay Interval:  [1,4]","Delay Interval:  [1,4]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (7,10]","Delay Interval:  (7,10]","Delay Interval:  (7,10]","Delay Interval:  (10,13]","Delay Interval:  (10,13]","Delay Interval:  (10,13]","Delay Interval:  (13,16]","Delay Interval:  (13,16]","Delay Interval:  (13,16]","Delay Interval:  (16,19]","Delay Interval:  (16,19]","Delay Interval:  (19,22]","Delay Interval:  (19,22]","Delay Interval:  (25,28]","Delay Interval:  (28,31]","Delay Interval:  (28,31]","Delay Interval:  (28,31]","Delay Interval:  (34,37]","Delay Interval:  (37,40]","Delay Interval:  (40,43]","Delay Interval:  (43,46]","Delay Interval:  (43,46]","Delay Interval:  (46,49]","Delay Interval:  (49,52]","Delay Interval:  (49,52]","Delay Interval:  (52,55]","Delay Interval:  (52,55]","Delay Interval:  (52,55]","Delay Interval:  (55,58]","Delay Interval:  (58,61]","Delay Interval:  (58,61]","Delay Interval:  (58,61]"],"marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39],"y":[10.199999999999998,10.499999999999995,10.199999999999998,8.7857142857142794,2.4444444444444384,11.428571428571427,4.4166666666666679,10.199999999999998,10.499999999999995,11.428571428571427,10.529411764705872,19.368421052631589,2.4444444444444451,7.0000000000003038,8.7857142857142794,11.428571428571427,7.0000000000003038,10.199999999999998,7.0000000000003038,8.7857142857142794,11.428571428571427,7.0000000000003038,11.428571428571427,8.7692307692307594,10.499999999999995,11.428571428571427,2.4444444444444384,7.0000000000003038,4.4166666666666679,4.4166666666666679,8.7857142857142794,8.7692307692307594,7.0000000000003038,10.199999999999998,8.7857142857142794,4.4166666666666679,8.7857142857142794,8.7692307692307594,4.4166666666666679],"type":"scatter","mode":"lines","name":"Predicted","line":{"color":"red"},"hoverinfo":["y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text","y+text"],"text":["Delay Interval:  [1,4]","Delay Interval:  [1,4]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (4,7]","Delay Interval:  (7,10]","Delay Interval:  (7,10]","Delay Interval:  (7,10]","Delay Interval:  (10,13]","Delay Interval:  (10,13]","Delay Interval:  (10,13]","Delay Interval:  (13,16]","Delay Interval:  (13,16]","Delay Interval:  (13,16]","Delay Interval:  (16,19]","Delay Interval:  (16,19]","Delay Interval:  (19,22]","Delay Interval:  (19,22]","Delay Interval:  (25,28]","Delay Interval:  (28,31]","Delay Interval:  (28,31]","Delay Interval:  (28,31]","Delay Interval:  (34,37]","Delay Interval:  (37,40]","Delay Interval:  (40,43]","Delay Interval:  (43,46]","Delay Interval:  (43,46]","Delay Interval:  (46,49]","Delay Interval:  (49,52]","Delay Interval:  (49,52]","Delay Interval:  (52,55]","Delay Interval:  (52,55]","Delay Interval:  (52,55]","Delay Interval:  (55,58]","Delay Interval:  (58,61]","Delay Interval:  (58,61]","Delay Interval:  (58,61]"],"marker":{"color":"rgba(255,127,14,1)","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>From the observed visual data, disparities between the anticipated and observed counts stand out, particularly within the intervals [1,4] and [4,7]. Nonetheless, it is imperative to quantify the model’s performance using metrics such as the Mean Squared Error (MSE) and Mean Absolute Error (MAE) to assess the real efficiency of the current model. These metrics will be compared against a baseline which is made of the MSE and MAE of the training data’s delay counts. In the analysis, the following values were obtained:</p>
<details>
<p><summary><b style="font-size:90%; border: 1px solid gray; border-radius: 5px; padding: 5px; ">Code Preview </b></p>
</summary>
<pre><code>baseline_predictions &lt;- rep(mean(training_data$delay_count), nrow(testing_data))

# Calculate MSE and MAE for the baseline model
baseline_mse &lt;- mean((actual_counts - baseline_predictions)^2)
baseline_mae &lt;- mean(abs(actual_counts - baseline_predictions))


# Calculate Model&#39;s MSE and MAE
mse &lt;- mean((actual_counts - predicted_counts)^2)
mae &lt;- mean(abs(actual_counts - predicted_counts))</code></pre>
</details>
<pre><code>## [1] &quot;Baseline MSE: 687.829606540645&quot;</code></pre>
<pre><code>## [1] &quot;Model MSE: 662.875473599456&quot;</code></pre>
<pre><code>## [1] &quot;Baseline MAE: 13.9761904761905&quot;</code></pre>
<pre><code>## [1] &quot;Model MAE: 12.7993394506493&quot;</code></pre>
<p>The results of the evaluation indicate that the baseline model achieves a lower MSE and MAE compared to the predictive model. These findings suggest that the baseline model performs slightly better than the predictive model in terms of both MSE and MAE. However, the differences between the metrics are relatively small. Nevertheless, further investigation and refinement of the predictive model may be necessary to achieve significant improvements in performance, particularly for intervals [1,4] and [4,7].</p>
</div>
<div id="strengths-limitations" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Strengths &amp; Limitations<a href="poisson-linear-regression.html#strengths-limitations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="strengths" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Strengths<a href="poisson-linear-regression.html#strengths" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Poisson regression stands out as an ideal method for examining phenomena such as occurrences of flight delays categorized by intervals, offering a robust framework for modeling events expressed as whole numbers. Its alignment with the Poisson distribution ensures accurate representation of count data dynamics, enhancing precision in modeling outcomes. Moreover, the model’s flexibility in handling various predictor types allows for versatile modeling approaches.</p>
</div>
<div id="limitations" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Limitations<a href="poisson-linear-regression.html#limitations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While powerful for count data analysis, comes with its share of limitations. The assumption of independence among events, while foundational, may not always reflect real-world scenarios accurately. Overdispersion, where the variance exceeds the mean, can inflate errors and compromise accuracy. Despite its flexibility in handling predictor variables, Poisson regression may struggle to capture complex relationships effectively, potentially limiting its predictive capabilities. Moreover, its sensitivity to outliers necessitates meticulous preprocessing to mitigate their influence on model stability.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-linear-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="binomial-linear-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/EliB29/AML/edit/main/02-linear-to-poisson.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/EliB29/AML/blob/main/02-linear-to-poisson.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
